CREATE TABLE usuario(
    id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(70) NOT NULL,
    senha VARCHAR(25) NOT NULL,
    data_cadastro DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE grupo(
    id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;